export const GET_USUARIOS_SUCCES = "GET_USUARIOS_SUCCES";
export const GET_USUARIOS_FAIL = "GET_USUARIOS_FAIL";

export const GET_USUARIOS_DETAIL_SUCCES =
  "GET_USUARIOS_DETAIL_SUCCES";
export const GET_USUARIOS_DETAIL_FAIL = "GET_USUARIOS_DETAIL_FAIL";
